SLADIM-131
ccims/CPU-tracking-monitoring-service pull request #5
Opened 2020-07-31 12:13 UTC by JonasJW

## Preparations
Please check if the PR fulfills these requirements
- [x] Readme (How to Install, Run, Use and Configure) wurde aktualisiert falls nötig
- [x] Das Feature ist dokumentiert
- [x] Alle nicht getter und setter Methoden sind dokumentiert
- [ ] Es wurden Unit tests für neue Features erstellt
- [ ] Alle Tests müssen erfolgreich sein
- [x] Mindestens ein Reviewer muss den Pull Request akzeptieren

## :ticket: Description

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
- Update of cpu-monitor-models
- Checking for minimum cpu value

* **What is the current behavior?** (You can also link to an open issue here)
- old cpu-monitor-models
- Only checking for critical cpu threshold

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

## :lock: Closes
Which issue(s) is (are) being closed by the PR?

2020-08-13 12:22 UTC, stiesssh requested changes
(1) wie vorhin bereits angesprochen: entfernt den initial endpoint
(2) einen sinnvollen test implementieren. da bei diesem PR u.a. eine prüfung des minimalen cpu wertes eingeführt wurde, wäre es z.b. sinnvoll, zu testen, dass beim unterschreiten des minimumalen wertes tatsächlich das dazu passende log erstellt wird. in wie fern das möglich ist, habe ich mir noch nicht angeschaut. evtl. revidiere ich diesen vorschlag später.

2020-08-13 12:51 UTC, buehlefs commented
Da diese PR eigentlich noch zum letzten Sprint zählt sollten wir die fehlende Testabdeckung von dem Feature lieber als Issue für den nächsten Sprint mit aufnehemen.

2020-08-13 13:46 UTC, stiesssh commented
oke. was ist mit dem initialen endpoint? darf der auch drinnen bleiben?

2020-08-13 14:08 UTC, buehlefs commented
Der muss wie besprochen noch raus bevor die PR gemerged werden kann.

2020-08-13 14:13 UTC, stiesssh commented
oke :)

2020-08-13 15:43 UTC, stiesssh commented
nicht nur auskommentieren, komplett entfernen! (so war zumindest mein verständnis der sache?)
das ganze auskommentieren sorgt nur für eine unmenge an auskommentierten code, der die lesbarkeit verschlechtert.

desweiteren war ich der ansicht das auch die zeilen 9 bis 15, also die definition dieses 'initialEndpoint' entfernt werden sollten? 
es erschließt sich mit schlicht nicht, warum dieser initail endpoint existiert. wenn ihr ihn also im code behalten wollt, möchte ich eine stichhaltige begründung seiner existenz.

2020-08-17 08:52 UTC, stiesssh approved these changes

2020-08-20 09:23 UTC, merged